//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesSadm2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesReporteLog
    {
        public int id { get; set; }
        public string folio_orden { get; set; }
        public string municipio_orden { get; set; }
        public string colonia_orden { get; set; }
        public string calle_orden { get; set; }
        public string puerta_orden { get; set; }
        public string contrato_orden { get; set; }
        public string comentarios_orden { get; set; }
        public string id_usuario_register { get; set; }
        public string nombre_usuario_register { get; set; }
        public Nullable<System.DateTime> fecha_register { get; set; }
        public string subcatego_orden { get; set; }
    }
}
